user_int = int(input('Enter integer (32 - 126):\n'))
user_float = float(input("Enter float:\n"))
user_char = str(input("Enter character:\n"))
user_string = str(input("Enter string:\n"))
print(user_int, end=' ')
print(user_float, end=' ')
print(user_char, end= ' ')
print(user_string)
print(user_string, end=' ')
print(user_char, end= ' ')
print(user_float, end=' ')
print(user_int)
print(user_int, 'converted to a character is', chr(user_int))